### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Kartikeya99** [JMPerez/spotify-dedup#117] opened 2020-11-09 15:40 UTC
On clicking on the login with the Spotify button, it does authenticate however the view doesn't change to what it should when successfully authenticated.

**Comment by brianazick** [comment] 2020-11-24 23:32
I see this issue as well, though I have been able to bypass it when accessing the site in MS Edge. I haven't been able to make it work in FireFox or Chrome, even with all extensions disabled.

**Comment by mvmisha** [comment] 2020-12-29 12:42
Doesn't work on Edge too

**Comment by JMPerez** [comment] 2020-12-29 14:21
@mvmisha please, try again. Looks like there was some change in a third party script that made the login fail.

**Comment by mvmisha** [comment] 2020-12-30 10:43
@JMPerez yep, works fine now 👌

**Comment by JMPerez** [comment] 2021-01-02 18:59
Closing this issue for now since the problem seems to be resolved. Feel free to reopen it if you can reproduce it again.

**Closed by JMPerez** 2021-01-02 18:59 UTC
