### ISSUE TITLE
Not working!!

### ISSUE THREAD

**Issue by ellenrjj** [JMPerez/spotify-dedup#158] opened 2024-05-03 16:27 UTC
the program isn't working, it won't remove duplicated songs. It shows the box to click but does not do anything.

**Comment by JMPerez** [comment] 2024-05-03 16:43
Thanks for the report! This is a duplicate of #157

**Comment by JMPerez** [comment] 2024-05-03 23:02
@ellenrjj The tool should be fixed now and be able to remove duplicates in playlists. For the time being, when there is a duplicate  due to songs with the same id, the duplicates will be removed and the same song will be added at the end of the playlist. This means that the original position of the duplicated song in the playlist won't be maintained.

**Closed by JMPerez** 2024-05-03 23:02 UTC

**Comment by ellenrjj** [comment] 2024-05-04 01:26
awesome!! thank you!
